version: "3.8"

networks:
  default: {}

services:
  nextjs:
    image: node:18
    working_dir: /scripts
    volumes:
      - ./:/scripts
    environment:
      - NODE_LOGGING_LEVEL=debug
    ports:
      - 3000:3000
    entrypoint: [bash, -c, "npm install && npm run build && npm run start"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: aUser
      POSTGRES_PASSWORD: aSecret
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 4s
      retries: 50
